myportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("portfolio.urls", namespace="portfolio")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("", views.home, name="home"),
    path("project/<int:pk>", views.project_detail, name="project_detail"),
    path("contact/", views.contact, name="contact"),
    path("subscribe/", views.subscribe, name="subscribe"),
]

templates/partials/footer.html
<footer class="footer bg-dark text-white py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h4>Contact Info</h4>
                <p class="mb-3">
                    <a href="mailto:moti@gmail.com" class="text-white">
                        <i class="far fa-envelope"></i> moti@gmail.com
                    </a>
                </p>
                <p>
                    <i class="fas fa-map-marker-alt"></i> Bhagalpur, Bihar, India
                </p>
            </div>
            <div class="col-md-6">
                <h4>Quick Links</h4>
                <ul class="list-unstyled d-flex flex-wrap">
                    <li class="m-2"><a href="#">Home</a></li>
                    <li class="m-2"><a href="#">Portfolio</a></li>
                    <li class="m-2"><a href="#">Services</a></li>
                    <li class="m-2"><a href="#">Blog</a></li>
                    <li class="m-2"><a href="#">Contact</a></li>
                </ul>
            </div>
        </div>
        <hr class="my-4" />
        <div class="row">
            <div class="col-md-6">
                <h4>Connect with Me</h4>
                <ul class="list-inline social-icons">
                    <li class="list-inline-item">
                        <a href="#" class="text-white">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" class="text-white">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.linkedin.com/in/moti9" class="text-white">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                    </li>
                    <!-- Add more social media links here -->
                </ul>
            </div>
            <div class="col-md-6">
                <h4>Stay Updated</h4>
                <form method="POST" action="{% url 'portfolio:subscribe' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="email" name="email" class="form-control" placeholder="Enter your email" required>
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">Subscribe</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</footer>

templates/partials/navbar.html
{% load static %}

<style>
  .navbar-brand {
    font-size: 24px;
    font-weight: bold;
    color: #fff;
    /* Text color */
  }

  .navbar-nav .nav-link {
    color: #fff;
    /* Text color */
    font-size: 18px;
    text-decoration: none;
    transition: color 0.3s ease;
    /* Smooth color transition on hover */
  }

  .nav-link:hover,
  .navbar-brand:hover {
    color: #04eaa1;
    /* Change to your preferred hover color */
  }
</style>

<div class="bg-dark text-bg-dark fw-bold sticky-top">
  <div class="d-flex justify-content-center">
    <img src="{% static 'image/portfolio.gif' %}" alt="header image" style="width: 8rem;">
  </div>
  <nav class="navbar navbar-expand-lg container">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Moti</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent"> <!-- Change to justify-content-end -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#projects">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>